{
  parserClass="io.github.nyub.selfieintellijplugin.language.SelfieParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Selfie"
  psiImplClassSuffix="Impl"
  psiPackage="io.github.nyub.selfieintellijplugin.language"
  psiImplPackage="io.github.nyub.selfieintellijplugin.language"

  elementTypeHolderClass="io.github.nyub.selfieintellijplugin.language.SelfieTypes"
  elementTypeClass="io.github.nyub.selfieintellijplugin.language.SelfieElementType"
  tokenTypeClass="io.github.nyub.selfieintellijplugin.language.SelfieTokenType"
}

selfieFile ::= snapshot+

snapshot ::= header NEW_LINE body

header ::= LEFT_CORNER header_path facet? RIGHT_CORNER

header_path ::= PATH_ELEMENT (PATH_SEPARATOR PATH_ELEMENT)*

facet ::= LEFT_BRACKET FACET_CONTENT RIGHT_BRACKET

body ::= SNAPSHOT_CONTENT {
    implements=["com.intellij.psi.PsiLanguageInjectionHost"]
    mixin="io.github.nyub.selfieintellijplugin.language.SelfieSnapshotBodyMixin"
}
